name: Auto build image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build image
    if: startswith(github.event.comment.body, '/imagebuild')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v1
      - name: Auto build image
        id: autobuild
        run: |
          commentbody="${{github.event.comment.body}}"
          echo ${commentbody}
          version=`echo "$commentbody"|cut -d" " -f2`
          echo "start to build kubernetes:$version"
          buildName=registry.cn-hangzhou.aliyuncs.com/onekey-io/kubernetes
          sudo wget https://github.com/sealerio/sealer/releases/download/v0.9.1/sealer-v0.9.1-linux-amd64.tar.gz && sudo tar -xvf sealer-v0.9.1-linux-amd64.tar.gz -C /usr/bin
          sudo sealer login ${{secrets.PRIVATEWAREHOUSE}}
          sudo sealer build -t ${buildName}:v${version} -f Kubefile .
          sudo sealer push ${buildName}:${version}
          echo "::set-output name=version::$version"
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Image ${{ steps.autobuild.outputs.version }} build successfully!
